name: Bingqi Huang
title: Bingqi Huang's Homepage
copyright: "Copyright &copy; Bingqi Huang 2025"

# Links
github_username: kkkjhgjhg4
license_url: https://github.com/kkkjhgjhg4/Bingqi.github.io/blob/master/LICENSE

# Home Section
home:
  subtitle: About Me

# News Section
news:
  subtitle: NEWS

# Publications Section
publications:
  subtitle: PUBLICATIONS

# Awards Section
awards:
  subtitle: AWARDS
